authors/urls.py
from django.urls import path

from . import views

app_name = "authors"

urlpatterns = [
    path('register/', views.register_view, name="register"),
    path('register/create/', views.register_create, name="create"),
]

recipes/urls.py
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path
from django.views.generic.base import RedirectView

from . import views

app_name = "recipes"

urlpatterns = [
    path('', views.home, name='home'),
    path('recipes/search/', views.search, name='search'),
    path('recipes/category/<int:category_id>/', views.category, name='category'), # noqa
    path('recipes/<int:id>/', views.recipe, name='recipe'),
]
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('/img/favicon.ico'))) # noqa
]

recipesProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('authors/', include('authors.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authors/models.py
from django.db import models

# Create your models here.

recipes/models.py
from django.contrib.auth.models import User
from django.db import models
from tinymce.models import HTMLField


class Category(models.Model):
    name = models.CharField(max_length=65)
    def __str__(self):
        return self.name


class Recipe(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug = models.SlugField(unique=True)
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=65)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=65)
    preparation_steps = HTMLField()
    preparation_steps_is_html = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(
        upload_to='recipes/covers/%Y/%m/%d', blank=True, default='', null=True)
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, blank=True, default=None) # noqa
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title

authors/forms.py
from django import forms
from django.contrib.auth.models import User


class RegisterForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
                'first_name', 
                'last_name',
                'username',
                'email',
                'password']

authors/views.py
from django.http import Http404
from django.shortcuts import render

from .forms import RegisterForm


def register_view(request):
    request.session['number'] = request.session.get['number']  or 1
    
    form = RegisterForm()

    return render(request, 'authors/pages/register_view.html', {
        'form': form
    })

def register_create(request):
    if not request.POST:
        raise Http404

    form = RegisterForm(request.POST)
    return render(request, 'authors/pages/register_view.html', {
        'form': form
    })

recipes/views.py
import os

from django.db.models import Q
from django.http.response import Http404
from django.shortcuts import get_list_or_404, get_object_or_404, render

from recipes.models import Recipe
from utils.pagination import make_pagination

PER_PAGE = int(os.environ.get('PER_PAGE', 9))

def home(request):
    #incluir o get_list_or_404 - apos producao. Devido ao erro do Pytest
    recipes = Recipe.objects.filter(
            is_published=True,
        ).order_by('-id')
    page_obj, pagination_range = make_pagination(request, recipes, PER_PAGE)
    return render(request, 'recipes/pages/home.html', context={
        'recipes': page_obj,
        'pagination_range': pagination_range
    })


def category(request, category_id):    
    # recipes = Recipe.objects.filter(
    #    category__id = category_id,
    #    is_published = True,
    # ).order_by('-id')

    # if not recipes:
    #    raise Http404('Not found 😢😢😢😢')
    # else: 
    #    return render(request, 'recipes/pages/category.html', context={
    #        'recipes': recipes,
    #        'title': f'{recipes.first().category.name}'
    # })

    recipes = get_list_or_404(
        Recipe.objects.filter(
            category__id=category_id,
            is_published=True,
        ).order_by('-id')
    )
    page_obj, pagination_range = make_pagination(request, recipes, PER_PAGE)
    return render(request, 'recipes/pages/category.html', context={
        'recipes': page_obj,
        'pagination_range': pagination_range,
        'title': f'{recipes[0].category.name}'
    })


def recipe(request, id):
    # recipe =  Recipe.objects.filter(ss
    #        pk = id,
    #        is_published = True
    #    ).order_by('-id').first()
    recipe = get_object_or_404(Recipe, id=id, is_published=True,)
    return render(request, 'recipes/pages/recipe-view.html', context={
        'recipe': recipe,
        'is_datail_page': True,
    })


def search(request):
  
    search_term = request.GET.get('q', '').strip()
    if not search_term:
        raise Http404()

    recipes = Recipe.objects.filter(
        Q(
            Q(title__icontains=search_term) |
            Q(description__icontains=search_term)
        ),
        is_published=True
    ).order_by('-id')

    page_obj, pagination_range = make_pagination(request, recipes, PER_PAGE)

    return render(request, 'recipes/pages/search.html', {
        'page_title': f'Search for "{ search_term }"',
        'search_term': search_term,
        'recipes': page_obj,
        'pagination_range': pagination_range,
        'additional_url_query': f'&q={ search_term }'
    })

authors/templates/authors/pages/register_view.html
{% extends 'global/base.html' %}

{% block title %}Register | {% endblock title%}

{% block content %}
    <div class="main content center container">
        <h2>Register {{ request.session.number }}</h2>
    </div>
    <div class="main content container">
        <form action="{% url 'authors:create' %}" method="POST">
            <div class="form-content form-content-grid">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        {% if field.help_text %}
                            <p class="help_text">
                                {{ field.help_text}}
                            </p>
                        {% endif %}
                        {{ field.errors }}
                    </div>
                {% endfor %}
            </div>
            <div class="form-group">
                <button type="submit">Send</button>
            </div>
         </form>
    </div>
{% endblock content %}

recipes/templates/recipes/pages/category.html
{% extends 'global/base.html' %}

{% block title %}{{ title }} - Category |{% endblock title %}

{% block content %}
    <div class="main-content main-content-list container">
        {% for recipe in recipes %}
            {% include 'recipes/partials/recipe.html' %}
        {% endfor %}
    </div>
{% endblock content %}

recipes/templates/recipes/pages/home.html
{% extends 'global/base.html' %}

{% block title %}Home |{% endblock title %}

{% block content %}
    {% include 'recipes/partials/messages.html' %}
    <div class="main-content main-content-list container">
        {% for recipe in recipes %}
            {% include 'recipes/partials/recipe.html' %}
        {% empty %}
            <div class="center">
                <h1>No recipes found here 😢</h1>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

recipes/templates/recipes/pages/recipe-view.html
{% extends 'global/base.html' %}


{% block title %}{{ recipe.title }} - ALTERAR |{% endblock title %}

{% block content %}
    <div class="main-content main-content-detail container">
        {% include 'recipes/partials/recipe.html' %}
    </div>
{% endblock content %}

recipes/templates/recipes/pages/search.html
{% extends 'global/base.html' %}

{% block title %}{{ page_title }} |{% endblock title %}

{% block content %}
    <div class="main-content main-content-list container">
        {% for recipe in recipes %}
            {% include 'recipes/partials/recipe.html' %}
        {% empty %}
            <div class="center">
                <h1>No recipes found here 😢</h1>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

recipes/templates/recipes/partials/footer.html
<footer class="main-footer">
    <div class="developer">
        <a href="http://www.sustavi.com.br/" target="_blank" rel="noreferrer noopener">By José Adriano de Lima</a>
    </div>

    <div class="powered">
        <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">Powered by Django</a>
    </div>
</footer> 

recipes/templates/recipes/partials/head.html
{% load static %}

<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/fontawesome.min.css"
    integrity="sha512-xX2rYBFJSj86W54Fyv1de80DWBq7zYLn2z0I9bIhQG+rxIF6XVJUpdGnsNHWRa6AvP89vtFupEPDP8eZAtu9qA=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/brands.min.css"
    integrity="sha512-OivR4OdSsE1onDm/i3J3Hpsm5GmOVvr9r49K3jJ0dnsxVzZgaOJ5MfxEAxCyGrzWozL9uJGKz6un3A7L+redIQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/solid.min.css"
    integrity="sha512-qzgHTQ60z8RJitD5a28/c47in6WlHGuyRvMusdnuWWBB6fZ0DWG/KyfchGSBlLVeqAz+1LzNq+gGZkCSHnSd3g=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">

<link rel="stylesheet" href="{% static 'recipes/css/styles.css' %}">

recipes/templates/recipes/partials/header.html
<link rel="shortcut icon" href="#">
<header class="main-header-container">
    <div class="main-header container">
        <h1>
            <a class="main-logo" href="{% url 'recipes:home' %}">
                <i class="fa-solid fa-utensils main-logo-icon"></i>
                <span class="main-logo-text"><h1>Recipes</h1></span>
            </a>
        </h1>
    </div>

</header>

recipes/templates/recipes/partials/messages.html
{% if messages %}
    <div class="main-content center container messages-containter ">
        {% for message in messages %}
            <div class="message {{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    </div>
{% endif %}

recipes/templates/recipes/partials/pagination.html
    {% if recipes.has_other_pages %}
        <div class="container pagination">
            <div class="pagination-content">
                {% if pagination_range.first_page_out_of_range %}
                     <a class ="page-link page-item" href="?page=1{{ additional_url_query }}">1</a>
                     <span class="page-item">...</span>
                {% endif %}
                {% for page in pagination_range.pagination  %}
                    {% if pagination_range.current_page == page %}
                        <a class ="page-link page-item page-current" href="?page={{ page }} {{ additional_url_query }}">{{ page }}</a>
                    {% else %}
                        <a class ="page-link page-item" href="?page={{ page }}{{ additional_url_query }}">{{ page }}</a>
                    {% endif %}
                {% endfor %}
                {% if pagination_range.last_page_out_of_range %}
                    <span class="page-item">...</span>

                    <a class ="page-link page-item" href="?page={{ pagination_range.total_pages }}{{ additional_url_query }}">{{ pagination_range.total_pages }}</a>
                     
                {% endif %}
            </div>
        </div>
    {% endif %}

recipes/templates/recipes/partials/recipe.html
<div class="recipe recipe-list-item">
    {% if recipe.cover.url is not Null%}
        <div class="recipe-cover">
            <a href="{% url 'recipes:recipe' recipe.id %}">
                <img class="recipe-image" src="{{ recipe.cover.url }}" alt="Temp">
            </a>
        </div>
    {% endif %}
    <div class="recipe-title-container">
        <a href="{% url 'recipes:recipe' recipe.id %}">
            <h2 class="recipe-title">{{ recipe.title }}</h2>
        </a>
    </div>
    <div class="recipe-author">
        {% if recipe.author is not None %}
            <span class="recipe-author-item">
                <i class="fas fa-user"></i>
                {% if recipe.author.first_name %}
                    {{ recipe.author.first_name }} {{ recipe.author.last_name }}
                {% else %}
                    {{ recipe.author.username }}
                {% endif %}
            </span>
        {% endif %}
        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{ recipe.created_at|date:"d/m/Y" }}
        </span>

        {% if recipe.category is not None %}
            {% if recipe.category.id is not None %}
                <span class="recipe-author-item">
                    <a href="{% url 'recipes:category'  recipe.category.id  %}">
                        <i class="fas fa-layer-group"></i>
                        <span>{{ recipe.category.name }}</span>
                    </a>
                </span>
            {% endif %}
        {% endif %}

    </div>

    <div class="recipe-content">
        <p>{{ recipe.description }}</p>
    </div>

    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i> Preparo</h3>
            <div class="recipe-meta-text">
                {{ recipe.preparation_time }} {{ recipe.preparation_time_unit }}
            </div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i> Porções</h3>
            <div class="recipe-meta-text">
                {{ recipe.servings }} {{ recipe.servings_unit }}
            </div>
        </div>
    </div>
    {% if is_datail_page is not True %}
        <footer class="recipe-footer">
            <a class="recipe-read-more button button-dark button-full-width" href="{% url 'recipes:recipe' recipe.id %}">
                <i class="fas fa-eye"></i>

                <span>ver mais...</span>
            </a>
        </footer>
    {% endif %}

     {% if is_detail_page is True %}
        <div class="preparation-steps">
            {% if recipe.preparation_steps_is_html %}
                {{ recipe.preparation_steps|safe}}
            {% else %}
                {{ recipe.preparation_steps|linebreaksbr}}
            {% endif %}
        </div>
     {% endif %}

</div>

recipes/templates/recipes/partials/search.html
    <div class="search-container">
        <div class="container">
            <form action="{% url 'recipes:search' %}" method="GET" class="search-form">
                <input type="search" class="search-input" name="q" value="{{ search_term }}" required>
                <button type="submit" class="search-button"><i class="fas fa-search"></i></button>
            </form>
        </div>
    </div>